[Support] Update the limit of RDS instances in dev
alphagov/paas-cf pull request #2607
Opened 2021-02-26 15:36 UTC by whi-tw

What
----
Update our hardcoded quota from 40 to 90 for dev.

```bash
$ gds aws paas-dev-admin -- aws service-quotas get-service-quota --service-code=rds --quota-code=L-7B6409FD
{
    "Quota": {
        "ServiceCode": "rds",
        "ServiceName": "Amazon Relational Database Service (Amazon RDS)",
        "QuotaArn": "arn:aws:servicequotas:eu-west-1:595665891067:rds/L-7B6409FD",
        "QuotaCode": "L-7B6409FD",
        "QuotaName": "DB instances",
        "Value": 90.0,
        "Unit": "None",
        "Adjustable": true,
        "GlobalQuota": false
    }
}
```
Perhaps we should get the correct quota from the API, rather than hardcoding it here?

How to review
-------------

Run down pipeline, ensure that the alert in dev stops being 'warning'

---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

2021-02-26 15:54 UTC, AP-Hunt requested changes
This should actually be changed in `default.yml` because in the Makefile, we have this line for the `dev` target

```$(eval export ENV_SPECIFIC_BOSH_VARS_FILE=default.yml)```

2021-02-26 16:03 UTC, whi-tw commented
> This should actually be changed in `default.yml` because in the Makefile, we have this line for the `dev` target
> 
> `$(eval export ENV_SPECIFIC_BOSH_VARS_FILE=default.yml)`

Agreed technically, although we need to rethink this approach, as the default quota is 40, whereas we have had this increased up to 90.

2021-02-26 16:08 UTC, AP-Hunt commented
Then let's consider doing the work to correct this.

2021-02-26 16:45 UTC, LeePorte commented
Sounds like a sensible thing to fix to me

2021-03-01 09:12 UTC, whi-tw commented
The alternative is to use the Quota API to pull in the current limit as a data point and use that for the alert. I've got some of the work for that done already in a branch, so I'll have a look - that'd be a much more reliable way of doing this, rather than the manual syncing we're doing right now.

2021-03-02 09:03 UTC, AP-Hunt requested changes
The pattern in `paas-metrics` for working with AWS services is to wrap them up in our own helper libraries, and test those. It would be good to do the same here for consistency.

2021-03-02 09:26 UTC, whi-tw commented
> The pattern in `paas-metrics` for working with AWS services is to wrap them up in our own helper libraries, and test those. It would be good to do the same here for consistency.

Confused. That's what I've done, right? I followed the same pattern as with the rds API

2021-03-02 09:28 UTC, whi-tw commented on tools/metrics/gauges_rds_db_instances.go
> +		QuotaCode:   aws.String("L-7B6409FD"),
The problem is, there's no real good reference to that string - for some reason, there are no results even if you google it. However, if you go to the URL [I've linked in the alert](https://console.aws.amazon.com/servicequotas/home?region=((aws_region))#!/services/rds/quotas/L-7B6409FD) it's definitely the right one. How would you suggest doing this?

2021-03-02 09:30 UTC, AP-Hunt commented on tools/metrics/gauges_rds_db_instances.go
> +		QuotaCode:   aws.String("L-7B6409FD"),
I think extract the constant and add just that explanation alongside it

2021-03-02 09:36 UTC, AP-Hunt commented
Err, yes it is. Sorry! I got confused between `awsservicequotas` and `servicequotas`. I was also expecting to see some changes to the `pkg/` directory in the main commit, having not realised you'd added that bit to the vendoring commit. My bad.

2021-03-02 09:36 UTC, AP-Hunt approved these changes

2021-03-02 09:52 UTC, whi-tw commented
> Err, yes it is. Sorry! I got confused between `awsservicequotas` and `servicequotas`. I was also expecting to see some changes to the `pkg/` directory in the main commit, having not realised you'd added that bit to the vendoring commit. My bad.

No trouble! Easily done! I wanted both commits to work independently and make sense, so I split them up in this way! I'll get this merged in!

2021-03-02 09:53 UTC, merged