[185302168] A script attaching peering security group for RDS
alphagov/paas-cf pull request #3225
Opened 2023-06-15 14:35 UTC by dark5un

What
----

We introduced a ruby script and make action which allows the creation of a security group against a predefined peering connection. This security group will in turn be attached to a specified RDS database to allow connectivity through that peer.

How to review
-------------

Follow the steps on the story.

---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

2023-06-16 15:00 UTC, AP-Hunt requested changes

2023-06-16 15:00 UTC, AP-Hunt commented on scripts/enable_vpc_peer_db_access.rb
> +  peering_entry = peering_data.find { |x| x["peer_name"] == peer_name }
What happens if the peering name isn't found?

2023-06-22 10:44 UTC, AP-Hunt commented
@dark5un Got a couple comments need addressing here

2023-06-22 11:23 UTC, dark5un commented
Review comments have been addressed

2023-06-22 12:56 UTC, AP-Hunt approved these changes
Looks good. Can you squash down the review fixes, please?

2023-06-23 10:16 UTC, dark5un commented
A more cleaning up and a new feature:
Providing env var DRY will force the script to run without any alterations to the database.

2023-06-23 13:59 UTC, merged